//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EEConfig.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EEConfig.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 An unofficial configuration utility for IE:EE games.
        ///Allows for easy changing many of the properties changeable through the Baldur.lua file.
        ///
        ///Icons provided by pixabay.com 的本地化字符串。
        /// </summary>
        internal static string About_Description {
            get {
                return ResourceManager.GetString("About_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This program is a fork of Nesae&apos;s IE-EE-Configuration project by MephistoSatanDevil, under the GPL-3.0 license. 的本地化字符串。
        /// </summary>
        internal static string AboutText_CreatedBy {
            get {
                return ResourceManager.GetString("AboutText_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Special thanks to: CamDawg, skellytz, Bubb &amp;&amp; Sam. for help during development. 的本地化字符串。
        /// </summary>
        internal static string AboutText_SpecialThanks {
            get {
                return ResourceManager.GetString("AboutText_SpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Infinity Engine - Enhanced Edition Configuration Utility 的本地化字符串。
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap config_gear {
            get {
                object obj = ResourceManager.GetObject("config_gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon config_gear_icon {
            get {
                object obj = ResourceManager.GetObject("config_gear_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown engine_mode &apos;{0}&apos; found in engine.lua. 的本地化字符串。
        /// </summary>
        internal static string Error_UnknownEngineMode {
            get {
                return ResourceManager.GetString("Error_UnknownEngineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Footsteps During Combat 的本地化字符串。
        /// </summary>
        internal static string ExtendedProgramConfigOneItem_DisableFootstepsDuringCombat {
            get {
                return ResourceManager.GetString("ExtendedProgramConfigOneItem_DisableFootstepsDuringCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Movies 的本地化字符串。
        /// </summary>
        internal static string ExtendedProgramConfigOneItem_DisableMovies {
            get {
                return ResourceManager.GetString("ExtendedProgramConfigOneItem_DisableMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strref On 的本地化字符串。
        /// </summary>
        internal static string ExtendedProgramConfigOneItem_StrrefOn {
            get {
                return ResourceManager.GetString("ExtendedProgramConfigOneItem_StrrefOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI Edit Mode 的本地化字符串。
        /// </summary>
        internal static string ExtendedProgramConfigOneItem_UIEditMode {
            get {
                return ResourceManager.GetString("ExtendedProgramConfigOneItem_UIEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reverse Mouse Wheel Zoom 的本地化字符串。
        /// </summary>
        internal static string ExtendedProgramConfigThreeItem_ReverseMouseWheelZoom {
            get {
                return ResourceManager.GetString("ExtendedProgramConfigThreeItem_ReverseMouseWheelZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Date On Pause 的本地化字符串。
        /// </summary>
        internal static string ExtendedProgramConfigThreeItem_ShowDateOnPause {
            get {
                return ResourceManager.GetString("ExtendedProgramConfigThreeItem_ShowDateOnPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Triggers On Tab 的本地化字符串。
        /// </summary>
        internal static string ExtendedProgramConfigThreeItem_ShowTriggersOnTab {
            get {
                return ResourceManager.GetString("ExtendedProgramConfigThreeItem_ShowTriggersOnTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Super Atomic Speed Fighting Action 的本地化字符串。
        /// </summary>
        internal static string ExtendedProgramConfigThreeItem_SuperAtomicSpeedFightingAction {
            get {
                return ResourceManager.GetString("ExtendedProgramConfigThreeItem_SuperAtomicSpeedFightingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Fog 的本地化字符串。
        /// </summary>
        internal static string ExtendedProgramConfigTwoItem_EnableFog {
            get {
                return ResourceManager.GetString("ExtendedProgramConfigTwoItem_EnableFog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enhanced Path Search 的本地化字符串。
        /// </summary>
        internal static string ExtendedProgramConfigTwoItem_EnhancedPathSearch {
            get {
                return ResourceManager.GetString("ExtendedProgramConfigTwoItem_EnhancedPathSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra Combat Info 的本地化字符串。
        /// </summary>
        internal static string ExtendedProgramConfigTwoItem_ExtraCombatInfo {
            get {
                return ResourceManager.GetString("ExtendedProgramConfigTwoItem_ExtraCombatInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force Dialog Pause 的本地化字符串。
        /// </summary>
        internal static string ExtendedProgramConfigTwoItem_ForceDialogPause {
            get {
                return ResourceManager.GetString("ExtendedProgramConfigTwoItem_ForceDialogPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All changes are saved automatically. 的本地化字符串。
        /// </summary>
        internal static string FooterText_ChangesSavedAutomatically {
            get {
                return ResourceManager.GetString("FooterText_ChangesSavedAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Game 的本地化字符串。
        /// </summary>
        internal static string GameName_UnknownGame {
            get {
                return ResourceManager.GetString("GameName_UnknownGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 30 AI Updates / Sec 的本地化字符串。
        /// </summary>
        internal static string GameSpeed_DisplayValue_Initial {
            get {
                return ResourceManager.GetString("GameSpeed_DisplayValue_Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Area Map Zoom 的本地化字符串。
        /// </summary>
        internal static string GraphicsItem_AreaMapZoom {
            get {
                return ResourceManager.GetString("GraphicsItem_AreaMapZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backend 的本地化字符串。
        /// </summary>
        internal static string GraphicsItem_Backend {
            get {
                return ResourceManager.GetString("GraphicsItem_Backend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable UI Scaling 的本地化字符串。
        /// </summary>
        internal static string GraphicsItem_EnableUIScaling {
            get {
                return ResourceManager.GetString("GraphicsItem_EnableUIScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Greyscale On Pause 的本地化字符串。
        /// </summary>
        internal static string GraphicsItem_GreyscaleOnPause {
            get {
                return ResourceManager.GetString("GraphicsItem_GreyscaleOnPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hardware Mouse Cursor 的本地化字符串。
        /// </summary>
        internal static string GraphicsItem_HardwareMouseCursor {
            get {
                return ResourceManager.GetString("GraphicsItem_HardwareMouseCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Black Space 的本地化字符串。
        /// </summary>
        internal static string GraphicsItem_ShowBlackSpace {
            get {
                return ResourceManager.GetString("GraphicsItem_ShowBlackSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Character Highlights 的本地化字符串。
        /// </summary>
        internal static string GraphicsItem_UseCharacterHighlights {
            get {
                return ResourceManager.GetString("GraphicsItem_UseCharacterHighlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Nearest Neighbour Scaling 的本地化字符串。
        /// </summary>
        internal static string GraphicsItem_UseNearestNeighbourScaling {
            get {
                return ResourceManager.GetString("GraphicsItem_UseNearestNeighbourScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Sprite Outlines 的本地化字符串。
        /// </summary>
        internal static string GraphicsItem_UseSpriteOutlines {
            get {
                return ResourceManager.GetString("GraphicsItem_UseSpriteOutlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window - Fullscreen 的本地化字符串。
        /// </summary>
        internal static string GraphicsItem_WindowFullscreen {
            get {
                return ResourceManager.GetString("GraphicsItem_WindowFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window - Maximized 的本地化字符串。
        /// </summary>
        internal static string GraphicsItem_WindowMaximized {
            get {
                return ResourceManager.GetString("GraphicsItem_WindowMaximized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom Lock 的本地化字符串。
        /// </summary>
        internal static string GraphicsItem_ZoomLock {
            get {
                return ResourceManager.GetString("GraphicsItem_ZoomLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  AI Updates / Sec 的本地化字符串。
        /// </summary>
        internal static string LabelText_AIUpdatesPerSecond {
            get {
                return ResourceManager.GetString("LabelText_AIUpdatesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string MenuItem_About {
            get {
                return ResourceManager.GetString("MenuItem_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Additional Options 的本地化字符串。
        /// </summary>
        internal static string MenuItem_AdditionalOptions {
            get {
                return ResourceManager.GetString("MenuItem_AdditionalOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup 的本地化字符串。
        /// </summary>
        internal static string MenuItem_Backup {
            get {
                return ResourceManager.GetString("MenuItem_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check 的本地化字符串。
        /// </summary>
        internal static string MenuItem_Check {
            get {
                return ResourceManager.GetString("MenuItem_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        internal static string MenuItem_Create {
            get {
                return ResourceManager.GetString("MenuItem_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string MenuItem_Exit {
            get {
                return ResourceManager.GetString("MenuItem_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string MenuItem_Help {
            get {
                return ResourceManager.GetString("MenuItem_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open GitHub 的本地化字符串。
        /// </summary>
        internal static string MenuItem_OpenGitHub {
            get {
                return ResourceManager.GetString("MenuItem_OpenGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Reference 的本地化字符串。
        /// </summary>
        internal static string MenuItem_OpenReference {
            get {
                return ResourceManager.GetString("MenuItem_OpenReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        internal static string MenuItem_Refresh {
            get {
                return ResourceManager.GetString("MenuItem_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore 的本地化字符串。
        /// </summary>
        internal static string MenuItem_Restore {
            get {
                return ResourceManager.GetString("MenuItem_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Utility 的本地化字符串。
        /// </summary>
        internal static string MenuItem_Utility {
            get {
                return ResourceManager.GetString("MenuItem_Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write Optimal Configuration 的本地化字符串。
        /// </summary>
        internal static string MenuItem_WriteOptimalConfiguration {
            get {
                return ResourceManager.GetString("MenuItem_WriteOptimalConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup successfully created! 的本地化字符串。
        /// </summary>
        internal static string MsgText_BackupCreatedSuccessfully {
            get {
                return ResourceManager.GetString("MsgText_BackupCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup creation failed! 的本地化字符串。
        /// </summary>
        internal static string MsgText_BackupCreationFailed {
            get {
                return ResourceManager.GetString("MsgText_BackupCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup file for {0} does not exist! 的本地化字符串。
        /// </summary>
        internal static string MsgText_BackupDoesNotExistInfo {
            get {
                return ResourceManager.GetString("MsgText_BackupDoesNotExistInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup file for {0} exists!
        ///
        ///Created at: {1} 的本地化字符串。
        /// </summary>
        internal static string MsgText_BackupExistsInfo {
            get {
                return ResourceManager.GetString("MsgText_BackupExistsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup successfully restored! 的本地化字符串。
        /// </summary>
        internal static string MsgText_BackupRestoredSuccessfully {
            get {
                return ResourceManager.GetString("MsgText_BackupRestoredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup Status 的本地化字符串。
        /// </summary>
        internal static string MsgText_BackupStatus {
            get {
                return ResourceManager.GetString("MsgText_BackupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot access game configuration properties. 的本地化字符串。
        /// </summary>
        internal static string MsgText_CannotAccessGameConfigProps {
            get {
                return ResourceManager.GetString("MsgText_CannotAccessGameConfigProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot check backup status. Configuration managers are not initialized. 的本地化字符串。
        /// </summary>
        internal static string MsgText_CannotCheckBackupStatus {
            get {
                return ResourceManager.GetString("MsgText_CannotCheckBackupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not automatically locate {0}. Please select it manually. 的本地化字符串。
        /// </summary>
        internal static string MsgText_CannotLocateConfigManuallySelect {
            get {
                return ResourceManager.GetString("MsgText_CannotLocateConfigManuallySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot open extended configuration. The game configuration properties are not accessible. Please ensure the configuration file is loaded first. 的本地化字符串。
        /// </summary>
        internal static string MsgText_CannotOpenExtendedConfig {
            get {
                return ResourceManager.GetString("MsgText_CannotOpenExtendedConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot refresh. Configuration file is not loaded or accessible. 的本地化字符串。
        /// </summary>
        internal static string MsgText_CannotRefresh {
            get {
                return ResourceManager.GetString("MsgText_CannotRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot restore backup! (Backup file might not exist or be invalid) 的本地化字符串。
        /// </summary>
        internal static string MsgText_CannotRestoreBackup {
            get {
                return ResourceManager.GetString("MsgText_CannotRestoreBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot restore backup. Configuration managers are not initialized. 的本地化字符串。
        /// </summary>
        internal static string MsgText_CannotRestoreBackupManagersNotInit {
            get {
                return ResourceManager.GetString("MsgText_CannotRestoreBackupManagersNotInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration has been backed up successfully. 的本地化字符串。
        /// </summary>
        internal static string MsgText_ConfigBackedUpSuccessfully {
            get {
                return ResourceManager.GetString("MsgText_ConfigBackedUpSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while trying to locate the configuration file: {0} 的本地化字符串。
        /// </summary>
        internal static string MsgText_ConfigLocateError {
            get {
                return ResourceManager.GetString("MsgText_ConfigLocateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration has not been backed up. 的本地化字符串。
        /// </summary>
        internal static string MsgText_ConfigNotBackedUp {
            get {
                return ResourceManager.GetString("MsgText_ConfigNotBackedUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The configuration file was not found for {0}. Ensure that the game is installed and was started at least once.
        ///
        ///The program will now quit. 的本地化字符串。
        /// </summary>
        internal static string MsgText_ConfigNotFound {
            get {
                return ResourceManager.GetString("MsgText_ConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration written! 的本地化字符串。
        /// </summary>
        internal static string MsgText_ConfigurationWritten {
            get {
                return ResourceManager.GetString("MsgText_ConfigurationWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirmation 的本地化字符串。
        /// </summary>
        internal static string MsgText_Confirmation {
            get {
                return ResourceManager.GetString("MsgText_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find required &apos;engine_name&apos; or &apos;engine_mode&apos; in engine.lua. 的本地化字符串。
        /// </summary>
        internal static string MsgText_CouldNotFindEngineNameOrMode {
            get {
                return ResourceManager.GetString("MsgText_CouldNotFindEngineNameOrMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not infer game name from the selected path: {0}. Using generic name for window title. 的本地化字符串。
        /// </summary>
        internal static string MsgText_CouldNotInferGameName {
            get {
                return ResourceManager.GetString("MsgText_CouldNotInferGameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not parse engine_mode value from engine.lua. 的本地化字符串。
        /// </summary>
        internal static string MsgText_CouldNotParseEngineMode {
            get {
                return ResourceManager.GetString("MsgText_CouldNotParseEngineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to create a new backup?
        ///
        ///Any existing backup will be overwritten. 的本地化字符串。
        /// </summary>
        internal static string MsgText_CreateBackupPrompt {
            get {
                return ResourceManager.GetString("MsgText_CreateBackupPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        internal static string MsgText_Information {
            get {
                return ResourceManager.GetString("MsgText_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to initialize configuration managers. The file path &apos;{Config.BaldurLuaPath}&apos; might be invalid or inaccessible. 的本地化字符串。
        /// </summary>
        internal static string MsgText_InitManagersFailed {
            get {
                return ResourceManager.GetString("MsgText_InitManagersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Option status has been refreshed! 的本地化字符串。
        /// </summary>
        internal static string MsgText_OptionStatusRefreshed {
            get {
                return ResourceManager.GetString("MsgText_OptionStatusRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The following changes will be written:
        ///
        ///- Set game speed to 40 AI Updates / Sec
        ///- Enable footsteps during combat
        ///- Enable date showing on pause
        ///- Enable enhanced path search
        ///- Disable cosmetic attacks
        ///
        ///Select OK to make changes. 的本地化字符串。
        /// </summary>
        internal static string MsgText_WriteOptimalChangesList {
            get {
                return ResourceManager.GetString("MsgText_WriteOptimalChangesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Banters 的本地化字符串。
        /// </summary>
        internal static string MultiplayerItem_DisableBanters {
            get {
                return ResourceManager.GetString("MultiplayerItem_DisableBanters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Chat Menu 的本地化字符串。
        /// </summary>
        internal static string MultiplayerItem_EnableChatMenu {
            get {
                return ResourceManager.GetString("MultiplayerItem_EnableChatMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Super Atomic Speed Fighting Action 的本地化字符串。
        /// </summary>
        internal static string PanelTitle_ExtendedProgramConfiguration {
            get {
                return ResourceManager.GetString("PanelTitle_ExtendedProgramConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GAME SPEED 的本地化字符串。
        /// </summary>
        internal static string PanelTitle_GameSpeed {
            get {
                return ResourceManager.GetString("PanelTitle_GameSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GRAPHICS 的本地化字符串。
        /// </summary>
        internal static string PanelTitle_Graphics {
            get {
                return ResourceManager.GetString("PanelTitle_Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MULTIPLAYER 的本地化字符串。
        /// </summary>
        internal static string PanelTitle_Multiplayer {
            get {
                return ResourceManager.GetString("PanelTitle_Multiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PROGRAM 的本地化字符串。
        /// </summary>
        internal static string PanelTitle_Program {
            get {
                return ResourceManager.GetString("PanelTitle_Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3D Acceleration 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsOneItem_3DAcceleration {
            get {
                return ResourceManager.GetString("ProgramOptionsOneItem_3DAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3E Thief Sneak Attack 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsOneItem_3EThiefSneakAttack {
            get {
                return ResourceManager.GetString("ProgramOptionsOneItem_3EThiefSneakAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Pause Center 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsOneItem_AutoPauseCenter {
            get {
                return ResourceManager.GetString("ProgramOptionsOneItem_AutoPauseCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug Mode 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsOneItem_DebugMode {
            get {
                return ResourceManager.GetString("ProgramOptionsOneItem_DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable Cosmetic Attacks 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsOneItem_DisableCosmeticAttacks {
            get {
                return ResourceManager.GetString("ProgramOptionsOneItem_DisableCosmeticAttacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Subtitles 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsOneItem_DisplaySubtitles {
            get {
                return ResourceManager.GetString("ProgramOptionsOneItem_DisplaySubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop Capitals 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsOneItem_DropCapitals {
            get {
                return ResourceManager.GetString("ProgramOptionsOneItem_DropCapitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Infravision 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsOneItem_Infravision {
            get {
                return ResourceManager.GetString("ProgramOptionsOneItem_Infravision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum HP 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsOneItem_MaximumHP {
            get {
                return ResourceManager.GetString("ProgramOptionsOneItem_MaximumHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Never Show Nuisance SOD 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsOneItem_NeverShowNuisanceSOD {
            get {
                return ResourceManager.GetString("ProgramOptionsOneItem_NeverShowNuisanceSOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nightmare Bonus XP 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsOneItem_NightmareBonusXP {
            get {
                return ResourceManager.GetString("ProgramOptionsOneItem_NightmareBonusXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Difficulty Based XP Bonus 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsOneItem_NoDifficultyBasedXPBonus {
            get {
                return ResourceManager.GetString("ProgramOptionsOneItem_NoDifficultyBasedXPBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pausing Map 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsOneItem_PausingMap {
            get {
                return ResourceManager.GetString("ProgramOptionsOneItem_PausingMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ranged Weapon Switching 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsOneItem_RangedWeaponSwitching {
            get {
                return ResourceManager.GetString("ProgramOptionsOneItem_RangedWeaponSwitching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Render Explored Map 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsOneItem_RenderExploredMap {
            get {
                return ResourceManager.GetString("ProgramOptionsOneItem_RenderExploredMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Character HP 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsOneItem_ShowCharacterHP {
            get {
                return ResourceManager.GetString("ProgramOptionsOneItem_ShowCharacterHP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sprite Mirror 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsOneItem_SpriteMirror {
            get {
                return ResourceManager.GetString("ProgramOptionsOneItem_SpriteMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Translucent Shadows 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsOneItem_TranslucentShadows {
            get {
                return ResourceManager.GetString("ProgramOptionsOneItem_TranslucentShadows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Active Campaign 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsThreeItem_ActiveCampaign {
            get {
                return ResourceManager.GetString("ProgramOptionsThreeItem_ActiveCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Learn Spell Info 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsThreeItem_AllLearnSpellInfo {
            get {
                return ResourceManager.GetString("ProgramOptionsThreeItem_AllLearnSpellInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Pause State 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsThreeItem_AutoPauseState {
            get {
                return ResourceManager.GetString("ProgramOptionsThreeItem_AutoPauseState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cloud Saves Enabled 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsThreeItem_CloudSavesEnabled {
            get {
                return ResourceManager.GetString("ProgramOptionsThreeItem_CloudSavesEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Dialog 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsThreeItem_ConfirmDialog {
            get {
                return ResourceManager.GetString("ProgramOptionsThreeItem_ConfirmDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate Floating Text 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsThreeItem_DuplicateFloatingText {
            get {
                return ResourceManager.GetString("ProgramOptionsThreeItem_DuplicateFloatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipment Comparison 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsThreeItem_EquipmentComparison {
            get {
                return ResourceManager.GetString("ProgramOptionsThreeItem_EquipmentComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter Games 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsThreeItem_FilterGames {
            get {
                return ResourceManager.GetString("ProgramOptionsThreeItem_FilterGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkeys On Tooltips 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsThreeItem_HotkeysOnTooltips {
            get {
                return ResourceManager.GetString("ProgramOptionsThreeItem_HotkeysOnTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Journal Popups 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsThreeItem_JournalPopups {
            get {
                return ResourceManager.GetString("ProgramOptionsThreeItem_JournalPopups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Over Confirm Everything 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsThreeItem_OverConfirmEverything {
            get {
                return ResourceManager.GetString("ProgramOptionsThreeItem_OverConfirmEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick Item Mapping 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsThreeItem_QuickItemMapping {
            get {
                return ResourceManager.GetString("ProgramOptionsThreeItem_QuickItemMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Render Travel Regions 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsThreeItem_RenderTravelRegions {
            get {
                return ResourceManager.GetString("ProgramOptionsThreeItem_RenderTravelRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show AOE 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsThreeItem_ShowAOE {
            get {
                return ResourceManager.GetString("ProgramOptionsThreeItem_ShowAOE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Learnable Spells 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsThreeItem_ShowLearnableSpells {
            get {
                return ResourceManager.GetString("ProgramOptionsThreeItem_ShowLearnableSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Message Box Hint 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsThreeItem_ShowMessageBoxHint {
            get {
                return ResourceManager.GetString("ProgramOptionsThreeItem_ShowMessageBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suppress Extra Difficulty Damage 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsThreeItem_SuppressExtraDifficultyDamage {
            get {
                return ResourceManager.GetString("ProgramOptionsThreeItem_SuppressExtraDifficultyDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tutorial State 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsThreeItem_TutorialState {
            get {
                return ResourceManager.GetString("ProgramOptionsThreeItem_TutorialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always Dither 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsTwoItem_AlwaysDither {
            get {
                return ResourceManager.GetString("ProgramOptionsTwoItem_AlwaysDither", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attack Sounds 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsTwoItem_AttackSounds {
            get {
                return ResourceManager.GetString("ProgramOptionsTwoItem_AttackSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Classic Selection Circles 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsTwoItem_ClassicSelectionCircles {
            get {
                return ResourceManager.GetString("ProgramOptionsTwoItem_ClassicSelectionCircles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cleric Ranger Spells 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsTwoItem_ClericRangerSpells {
            get {
                return ResourceManager.GetString("ProgramOptionsTwoItem_ClericRangerSpells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Circles 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsTwoItem_ColorCircles {
            get {
                return ResourceManager.GetString("ProgramOptionsTwoItem_ColorCircles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Combat UI 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsTwoItem_CombatUI {
            get {
                return ResourceManager.GetString("ProgramOptionsTwoItem_CombatUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Critical Hit Screen Shake 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsTwoItem_CriticalHitScreenShake {
            get {
                return ResourceManager.GetString("ProgramOptionsTwoItem_CriticalHitScreenShake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Environmental Audio 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsTwoItem_EnvironmentalAudio {
            get {
                return ResourceManager.GetString("ProgramOptionsTwoItem_EnvironmentalAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expire Trap Highlights 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsTwoItem_ExpireTrapHighlights {
            get {
                return ResourceManager.GetString("ProgramOptionsTwoItem_ExpireTrapHighlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra Feedback 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsTwoItem_ExtraFeedback {
            get {
                return ResourceManager.GetString("ProgramOptionsTwoItem_ExtraFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Footsteps 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsTwoItem_Footsteps {
            get {
                return ResourceManager.GetString("ProgramOptionsTwoItem_Footsteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Heal Party On Rest 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsTwoItem_HealPartyOnRest {
            get {
                return ResourceManager.GetString("ProgramOptionsTwoItem_HealPartyOnRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HP Over Head 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsTwoItem_HPOverHead {
            get {
                return ResourceManager.GetString("ProgramOptionsTwoItem_HPOverHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nightmare Bonus Gold 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsTwoItem_NightmareBonusGold {
            get {
                return ResourceManager.GetString("ProgramOptionsTwoItem_NightmareBonusGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Render Actions 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsTwoItem_RenderActions {
            get {
                return ResourceManager.GetString("ProgramOptionsTwoItem_RenderActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subtitles 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsTwoItem_Subtitles {
            get {
                return ResourceManager.GetString("ProgramOptionsTwoItem_Subtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Terrain Hugging 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsTwoItem_TerrainHugging {
            get {
                return ResourceManager.GetString("ProgramOptionsTwoItem_TerrainHugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weather 的本地化字符串。
        /// </summary>
        internal static string ProgramOptionsTwoItem_Weather {
            get {
                return ResourceManager.GetString("ProgramOptionsTwoItem_Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} AI Updates / Sec 的本地化字符串。
        /// </summary>
        internal static string SpeedValueDisplayFormat {
            get {
                return ResourceManager.GetString("SpeedValueDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CONFIGURATION FOUND 的本地化字符串。
        /// </summary>
        internal static string Status_ConfigurationFound {
            get {
                return ResourceManager.GetString("Status_ConfigurationFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CONFIGURATION NOT FOUND 的本地化字符串。
        /// </summary>
        internal static string Status_ConfigurationNotFound {
            get {
                return ResourceManager.GetString("Status_ConfigurationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the game 的本地化字符串。
        /// </summary>
        internal static string TheGame {
            get {
                return ResourceManager.GetString("TheGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} - Configuration 的本地化字符串。
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
